# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 消费者前端CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  blb-seller-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm --prefix ./blb-seller-frontend/ ci
    - run: npm --prefix ./blb-seller-frontend/ run build --if-present
    - run: npm --prefix ./blb-seller-frontend/ test
      env:
        CI: true
